### ISSUE TITLE
Certifikát na iapi.iplatebnibrana.csob.cz

### ISSUE THREAD

**Issue by kukulich** [csob/paymentgateway#625] opened 2022-04-25 14:28 UTC
Bylo by možné opravit nastavení cerfifikátu na iapi.iplatebnibrana.csob.cz?

Viz  https://www.ssllabs.com/ssltest/analyze.html?d=iapi.iplatebnibrana.csob.cz

Dostáváme aktuálně chyby typu: `cURL error 60: Peer's certificate issuer has been marked as not trusted by the user.`

**Comment by Garreat** [comment] 2022-04-25 16:38
@janbrasna I have already excluded the insecure ciphers mentioned in the email but there's still more ECDSAs on my list. Gonna wipe them all and let you know.

**Comment by horakmichal91** [comment] 2022-04-25 18:05
Dear all,

I noticed dkomarek2 about this. Your request has been forwarded to him. He will inform you accordingly about next step.

Regards,

Bc. Michal Horák

**Comment by horakmichal91** [comment] 2022-04-25 18:05
Dear all,

I noticed dkomarek2 about this. Your request has been forwarded to him. He will inform you accordingly about next step.

Regards,

Bc. Michal Horák
IT Support Specialist

**Comment by Garreat** [comment] 2022-04-25 18:42
@janbrasna After disabling all ECDSA ciphers, things work as intended.
Perhaps the server should just reject negotiation of those ciphers but we're good now. Thank you.

**Comment by janlanger** [comment] 2022-04-25 19:18
Problém nastává v případě že klient nepodporuje TLS 1.3. U TLS 1.2 server preferuje šifry s ECDSA ke kterým ale poskytuje self signed certifikát...

```sh
$ curl -vvv --location -k --tls-max 1.2 --request GET 'https://iapi.iplatebnibrana.csob.cz/api/v1.8/'
Note: Unnecessary use of -X or --request, GET is already inferred.
*   Trying 193.245.38.104:443...
* TCP_NODELAY set
* Connected to iapi.iplatebnibrana.csob.cz (193.245.38.104) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: C:/Program Files/Git/mingw64/ssl/certs/ca-bundle.crt
  CApath: none
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-ECDSA-AES128-GCM-SHA256
* ALPN, server did not agree to a protocol
* Server certificate:
*  subject: CN=iplatebnibrana.csob.cz
*  start date: Apr 22 09:34:21 2022 GMT
*  expire date: Apr 17 09:34:21 2023 GMT
*  issuer: C=CZ; ST=Czech Republic; L=Praha; O=Monet; CN=Monet Common CA
*  SSL certificate verify result: self signed certificate in certificate chain (19), continuing anyway.
> GET /api/v1.8/ HTTP/1.1
> Host: iapi.iplatebnibrana.csob.cz
> User-Agent: curl/7.65.3
> Accept: */*
```

Přijde mi tedy že server není nakonfigurován správně.

**Comment by janbrasna** [comment] 2022-04-25 19:21
@Garreat It's actually the other way around, there's an ongoing intent to add ECC chains that weren't present before, as to help supporting Windows Server 2012 R2 clients that were affected by #622 with no suites left to match for handshake. Nonetheless until the correct EV ECC cert in hybrid RSA/ECDSA operation is in place the EC suites should've been on the bottom of the list as a last resort only for now (mainly to verify effectiveness of the addition for affected systems), not the first in the preferred order.

So for now if you disable ECDSAs, prefer/prioritise/pick any of the RSAs available explicitly for your connections, or enforce TLS 1.3 only, you should be good for the time being — until this is fixed on the server.

_(However the ECDSA's performance makes them the ideal choice as first in the order of preference, so once this is correctly accompanied by an ECC EV cert it should make the top of the list eventually. Once this is sorted out you should allow the ECDSA GCMs back, someone will let you know once this issue is resolved.)_

**Comment by kukulich** [comment] 2022-04-26 11:00
It looks it works now: https://www.ssllabs.com/ssltest/analyze.html?d=iapi.iplatebnibrana.csob.cz

**Comment by janbrasna** [comment] 2022-04-26 11:57
@kukulich Je to tak, ty EC chainy jsou vypnute nez se problem vyresi. Diky za report!

@janlanger Urcite, vidim to stejne, diky za introspekci. Support resi kompatibilitu pro nejake merchanty, ale pro tato overovaci spojeni bude potreba bud upravit poradi nebo pockat na ostre certy, rozhodne nemely skoncit mezi preferovanymi. 

Cilem je nicmene podporu ECC pridat, snad to bude mit brzy reseni.

**Closed** 2022-07-03 14:04 UTC
Labels: bug, resolved, underway

**Comment by janbrasna** [comment] 2022-07-03 14:09
@Garreat Just a heads up, the EC chains are configured in prod-level settings now (EV etc.) so if you fancy enabling them back you should have a more modern chains as defaults now.

> ![Screenshot 2022-07-03 at 16 08 10](https://user-images.githubusercontent.com/1784648/177043520-05050fc7-fbd1-4d15-be96-1b7293628eda.png)
